# Generated by Django 3.0.9 on 2020-09-15 05:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDeatials',
            new_name='UserDetails',
        ),
    ]
