# Generated by Django 3.0.9 on 2020-09-15 06:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_course_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content',
            new_name='descriptionCourse',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Started', 'Started'), ('Completed', 'Completed')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionContent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('Coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Course')),
            ],
        ),
    ]
