# Generated by Django 3.0.9 on 2020-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200915_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='ContentName',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
