# Generated by Django 3.0.9 on 2020-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_coursecontent_contentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('CurrentAfairs', 'Current Afairs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.CharField(choices=[('NotStarted', 'Not Started'), ('Started', 'Started'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
