# Generated by Django 3.0.9 on 2020-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200915_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
    ]
