# Generated by Django 3.0.9 on 2020-09-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_coursecontent_isfree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='CatName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
            preserve_default=False,
        ),
    ]
