# Generated by Django 3.0.9 on 2020-09-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200915_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CatName',
        ),
    ]
