# Generated by Django 3.0.9 on 2020-09-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_course_catname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('CurrentAfairs', 'Current Afairs')], default=6, max_length=20),
            preserve_default=False,
        ),
    ]
