# Generated by Django 3.0.9 on 2020-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200918_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('courseName', models.CharField(max_length=50)),
                ('now', models.IntegerField()),
            ],
        ),
    ]
