# Generated by Django 3.0.9 on 2020-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='Coursename',
            field=models.CharField(max_length=50),
        ),
    ]
